/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ht": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_ht_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user and start a session
         * @description Creates a user, signs in immediately and sets the `session_id` HTTP-only cookie. No separate login call is required after success.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and set the session cookie */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Terminate the current session
         * @description Idempotent: clears the `session_id` cookie and revokes the current session if present. Always returns 200, including when no session is sent.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke every active session for the current user */
        post: operations["logout_all_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated public user directory
         * @description Anonymous users are excluded. Results are cached.
         */
        get: operations["get_users_feed_api_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile of the authenticated user */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        /**
         * Anonymize the authenticated account
         * @description Performs a soft-delete: the row is preserved but the username is replaced with `deleted-<id>`, personal fields are wiped, the avatar is removed, the bio is dropped and all sessions are revoked. The operation is irreversible.
         */
        delete: operations["delete_me_api_v1_users_me_delete"];
        options?: never;
        head?: never;
        /** Partially update the authenticated user's profile */
        patch: operations["update_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload (replace) the authenticated user's avatar
         * @description Multipart upload. The image is re-encoded server-side to WebP and the previous avatar (if any) is deleted. Allowed input types are the values in `ALLOWED_IMAGE_CONTENT_TYPES`.
         */
        put: operations["upload_avatar_api_v1_users_me_avatar_put"];
        post?: never;
        /**
         * Remove the authenticated user's avatar
         * @description Clears `avatar_key` and deletes the stored object. Idempotent: returns 204 even when no avatar was set.
         */
        delete: operations["delete_avatar_api_v1_users_me_avatar_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/bio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upsert the authenticated user's bio
         * @description Creates the bio row if missing, otherwise patches the provided fields. Empty strings for phone/vk/max links clear the value.
         */
        put: operations["update_bio_api_v1_users_me_bio_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public profile by username */
        get: operations["get_user_api_v1_users__username__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{username}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated posts authored by a given user */
        get: operations["get_user_posts_api_v1_users__username__posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated post feed with optional filters
         * @description Anonymous-friendly. The unfiltered feed (no category, tags or date range) is cached; any filter combination bypasses the cache.
         */
        get: operations["list_feed_api_v1_posts_get"];
        put?: never;
        /** Create a post authored by the current user */
        post: operations["create_post_api_v1_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a single post
         * @description Anonymous-friendly. The `my_reaction` field is populated only when the caller is authenticated; it is `null` otherwise.
         */
        get: operations["get_post_api_v1_posts__post_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a post (author or admin)
         * @description Removes the post row and its photo from storage. Hard delete.
         */
        delete: operations["delete_post_api_v1_posts__post_id__delete"];
        options?: never;
        head?: never;
        /**
         * Partially update a post (author only)
         * @description Admins cannot edit foreign posts, only delete them.
         */
        patch: operations["update_post_api_v1_posts__post_id__patch"];
        trace?: never;
    };
    "/api/v1/posts/{post_id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload (replace) the post's photo (author only)
         * @description Multipart upload. Re-encoded server-side to WebP; the previous photo, if any, is deleted from storage.
         */
        post: operations["upload_photo_api_v1_posts__post_id__photo_post"];
        /**
         * Remove a post's photo (author only)
         * @description Clears `photo_key` and deletes the stored object. Idempotent: returns 204 even when no photo was attached.
         */
        delete: operations["delete_photo_api_v1_posts__post_id__photo_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{post_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated comments for a post */
        get: operations["list_comments_api_v1_posts__post_id__comments_get"];
        put?: never;
        /** Create a comment on a post */
        post: operations["create_comment_api_v1_posts__post_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{post_id}/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a comment (author or admin) */
        delete: operations["delete_comment_api_v1_posts__post_id__comments__comment_id__delete"];
        options?: never;
        head?: never;
        /**
         * Edit a comment (author only)
         * @description Admins cannot edit foreign comments, only delete them.
         */
        patch: operations["update_comment_api_v1_posts__post_id__comments__comment_id__patch"];
        trace?: never;
    };
    "/api/v1/posts/{post_id}/reactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle the caller's reaction on a post
         * @description Single endpoint with toggle semantics:
         *
         *     - no existing reaction → the reaction is added;
         *     - existing reaction of the same type → it is removed (`my_reaction` becomes `null`);
         *     - existing reaction of a different type → it is replaced.
         *
         *     The response always carries the up-to-date counts and the caller's current reaction after the operation.
         */
        post: operations["toggle_reaction_api_v1_posts__post_id__reactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every tag in the catalog */
        get: operations["list_tags_api_v1_tags_get"];
        put?: never;
        /** Create a tag (admin only) */
        post: operations["create_tag_api_v1_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AvatarUploadResponse */
        AvatarUploadResponse: {
            /** Avatar Url */
            avatar_url: string;
        };
        /** BioSchema */
        BioSchema: {
            /** About */
            about?: string | null;
            /** Phone Number */
            phone_number?: string | null;
            /** Email */
            email?: string | null;
            /** Vk Link */
            vk_link?: string | null;
            /** Max Link */
            max_link?: string | null;
        };
        /**
         * BioUpdateSchema
         * @description Partial bio update. Empty strings for phone/vk/max links are treated as clear.
         */
        BioUpdateSchema: {
            /** About */
            about?: string | null;
            /**
             * Phone Number
             * @description Russian phone in E.164: `+7XXXXXXXXXX`.
             * @example +79991234567
             */
            phone_number?: string | null;
            /** Email */
            email?: string | null;
            /**
             * Vk Link
             * @description Must start with `https://vk.com/` or `https://vk.ru/`.
             * @example https://vk.com/username
             */
            vk_link?: string | null;
            /**
             * Max Link
             * @description Must start with `https://max.ru/`.
             * @example https://max.ru/username
             */
            max_link?: string | null;
        };
        /** Body_upload_avatar_api_v1_users_me_avatar_put */
        Body_upload_avatar_api_v1_users_me_avatar_put: {
            /** File */
            file: string;
        };
        /** Body_upload_photo_api_v1_posts__post_id__photo_post */
        Body_upload_photo_api_v1_posts__post_id__photo_post: {
            /** File */
            file: string;
        };
        /** CommentCreateSchema */
        CommentCreateSchema: {
            /** Text */
            text: string;
        };
        /** CommentSchema */
        CommentSchema: {
            /** Pk */
            pk: number;
            /** Text */
            text: string;
            author: components["schemas"]["UserLightSchema"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CommentUpdateSchema */
        CommentUpdateSchema: {
            /** Text */
            text: string;
        };
        /**
         * ErrorResponse
         * @description Uniform error envelope returned by all non-2xx responses.
         * @example {
         *       "detail": "Not found"
         *     }
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginSchema */
        LoginSchema: {
            /**
             * Username
             * @description URL-safe handle: lowercase letters, digits and hyphens; starts with a letter, ends with a letter or digit; no consecutive hyphens.
             * @example john-doe
             */
            username: string;
            /** Password */
            password: string;
        };
        /** PaginatedResult[CommentSchema] */
        PaginatedResult_CommentSchema_: {
            /** Items */
            items: components["schemas"]["CommentSchema"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PaginatedResult[PostLightSchema] */
        PaginatedResult_PostLightSchema_: {
            /** Items */
            items: components["schemas"]["PostLightSchema"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PaginatedResult[UserLightSchema] */
        PaginatedResult_UserLightSchema_: {
            /** Items */
            items: components["schemas"]["UserLightSchema"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PhotoUploadResponse */
        PhotoUploadResponse: {
            /** Photo Url */
            photo_url: string;
        };
        /**
         * PostCategory
         * @enum {string}
         */
        PostCategory: "story" | "event" | "help" | "volunteer" | "news";
        /** PostCreateSchema */
        PostCreateSchema: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** @default story */
            category: components["schemas"]["PostCategory"];
            /** External Url */
            external_url?: string | null;
            /** Tag Ids */
            tag_ids?: number[];
        };
        /** PostLightSchema */
        PostLightSchema: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            category: components["schemas"]["PostCategory"];
            /** Photo Url */
            photo_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PostSchema */
        PostSchema: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            category: components["schemas"]["PostCategory"];
            /** Photo Url */
            photo_url?: string | null;
            /** External Url */
            external_url?: string | null;
            author: components["schemas"]["UserLightSchema"];
            /** Tags */
            tags: components["schemas"]["TagSchema"][];
            reactions: components["schemas"]["ReactionCountsSchema"];
            my_reaction?: components["schemas"]["ReactionType"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PostUpdateSchema */
        PostUpdateSchema: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            category?: components["schemas"]["PostCategory"] | null;
            /** External Url */
            external_url?: string | null;
            /** Tag Ids */
            tag_ids?: number[] | null;
        };
        /** ReactionCountsSchema */
        ReactionCountsSchema: {
            /**
             * Like
             * @default 0
             */
            like: number;
            /**
             * Support
             * @default 0
             */
            support: number;
            /**
             * Inspiring
             * @default 0
             */
            inspiring: number;
        };
        /** ReactionToggleResponse */
        ReactionToggleResponse: {
            counts: components["schemas"]["ReactionCountsSchema"];
            my_reaction: components["schemas"]["ReactionType"] | null;
        };
        /** ReactionToggleSchema */
        ReactionToggleSchema: {
            reaction: components["schemas"]["ReactionType"];
        };
        /**
         * ReactionType
         * @enum {string}
         */
        ReactionType: "like" | "support" | "inspiring";
        /** RegisterResponseSchema */
        RegisterResponseSchema: {
            /** User Id */
            user_id: number;
            /** Username */
            username: string;
        };
        /** RegisterSchema */
        RegisterSchema: {
            /**
             * Username
             * @description URL-safe handle: lowercase letters, digits and hyphens; starts with a letter, ends with a letter or digit; no consecutive hyphens.
             * @example john-doe
             */
            username: string;
            /** Password */
            password: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /** TagCreateSchema */
        TagCreateSchema: {
            /** Name */
            name: string;
        };
        /** TagSchema */
        TagSchema: {
            /** Pk */
            pk: number;
            /** Name */
            name: string;
        };
        /** UserLightSchema */
        UserLightSchema: {
            /** Pk */
            pk: number;
            /** Username */
            username: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /** UserSchema */
        UserSchema: {
            /** Pk */
            pk: number;
            /** Username */
            username: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Is Admin */
            is_admin: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            bio?: components["schemas"]["BioSchema"] | null;
        };
        /** UserUpdateSchema */
        UserUpdateSchema: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthcheck_ht_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponseSchema"];
                };
            };
            /** @description Username already taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Invalid credentials or account deactivated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_all_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_users_feed_api_v1_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResult_UserLightSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSchema"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_me_api_v1_users_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSchema"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_avatar_api_v1_users_me_avatar_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_avatar_api_v1_users_me_avatar_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarUploadResponse"];
                };
            };
            /** @description Image exceeds size limit or is unreadable. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported image content type. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_avatar_api_v1_users_me_avatar_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_bio_api_v1_users_me_bio_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BioUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BioSchema"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_user_api_v1_users__username__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSchema"];
                };
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_posts_api_v1_users__username__posts_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResult_PostLightSchema_"];
                };
            };
            /** @description User not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feed_api_v1_posts_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["PostCategory"] | null;
                tag_ids?: number[] | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResult_PostLightSchema_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_post_api_v1_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostSchema"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_post_api_v1_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostSchema"];
                };
            };
            /** @description Post not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_post_api_v1_posts__post_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller is neither the post author nor an admin. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Post not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_post_api_v1_posts__post_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostSchema"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller is neither the post author nor an admin. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Post not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_photo_api_v1_posts__post_id__photo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_photo_api_v1_posts__post_id__photo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoUploadResponse"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller is not the post author. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Post not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_photo_api_v1_posts__post_id__photo_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller is not the post author. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Post not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_comments_api_v1_posts__post_id__comments_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResult_CommentSchema_"];
                };
            };
            /** @description Post not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_comment_api_v1_posts__post_id__comments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentSchema"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Post not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_comment_api_v1_posts__post_id__comments__comment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
                comment_id: number;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller is neither the comment author nor an admin. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Post or comment not found, or comment does not belong to the post. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_comment_api_v1_posts__post_id__comments__comment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
                comment_id: number;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentSchema"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Caller is not the comment author. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Post or comment not found, or comment does not belong to the post. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    toggle_reaction_api_v1_posts__post_id__reactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReactionToggleSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReactionToggleResponse"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Post not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_tags_api_v1_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagSchema"][];
                };
            };
        };
    };
    create_tag_api_v1_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session_id?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagSchema"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Admin privileges required. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tag with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded. `Retry-After` header indicates the window in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
